@echo off
cd /d %~dp0
echo Starting Future Weaver Desktop App...
echo Ensuring dependencies are installed...
pip install -r requirements.txt
echo Launching Application...
python main.py
pause
