// This file is automatically generated. Do not edit it directly.
// MOCKED FOR PYTHON DESKTOP APP CONVERSION
// This allows the app to build without relying on real Supabase connection
// and prevents errors in hooks we haven't explicitely converted to CSV.

const mockSupabase = {
  from: (table: string) => {
    console.log(`[MockSupabase] Accessed table: ${table}`);
    const chain = {
      select: () => chain,
      order: () => Promise.resolve({ data: [], error: null }),
      eq: () => chain,
      neq: () => chain,
      gt: () => chain,
      lt: () => chain,
      gte: () => chain,
      lte: () => chain,
      like: () => chain,
      ilike: () => chain,
      is: () => chain,
      in: () => chain,
      contains: () => chain,
      containedBy: () => chain,
      rangeGt: () => chain,
      rangeLt: () => chain,
      rangeGte: () => chain,
      rangeLte: () => chain,
      rangeAdjacent: () => chain,
      overlaps: () => chain,
      textSearch: () => chain,
      match: () => chain,
      not: () => chain,
      or: () => chain,
      filter: () => chain,
      limit: () => chain,
      single: () => Promise.resolve({ data: null, error: null }),
      maybeSingle: () => Promise.resolve({ data: null, error: null }),
      csv: () => Promise.resolve({ data: null, error: null }),
      insert: () => Promise.resolve({ data: null, error: null }),
      upsert: () => Promise.resolve({ data: null, error: null }),
      update: () => Promise.resolve({ data: null, error: null }),
      delete: () => Promise.resolve({ data: null, error: null }),
      then: (resolve: any) => resolve({ data: [], error: null }) // For await compatibility on select directly
    };
    return chain;
  },
  channel: () => ({
    on: () => ({ subscribe: () => { } }),
    subscribe: () => { }
  }),
  auth: {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    signOut: () => Promise.resolve({ error: null }),
  },
  storage: {
    from: () => ({
      upload: () => Promise.resolve({ data: null, error: null }),
      getPublicUrl: () => ({ data: { publicUrl: '' } }),
    })
  }
};

export const supabase = mockSupabase as any;